# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.coach_pb2 as coach__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coach_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoachChatServiceStub(object):
    """=============================================
    Service 1 - Coach Chat
    =============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/coachpb.CoachChatService/SendMessage',
                request_serializer=coach__pb2.ChatRequest.SerializeToString,
                response_deserializer=coach__pb2.ChatResponse.FromString,
                _registered_method=True)


class CoachChatServiceServicer(object):
    """=============================================
    Service 1 - Coach Chat
    =============================================
    """

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoachChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=coach__pb2.ChatRequest.FromString,
                    response_serializer=coach__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coachpb.CoachChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coachpb.CoachChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoachChatService(object):
    """=============================================
    Service 1 - Coach Chat
    =============================================
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coachpb.CoachChatService/SendMessage',
            coach__pb2.ChatRequest.SerializeToString,
            coach__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkoutGeneratorServiceStub(object):
    """=============================================
    Service 2 - Workout Generator
    =============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateWorkout = channel.unary_unary(
                '/coachpb.WorkoutGeneratorService/GenerateWorkout',
                request_serializer=coach__pb2.WorkoutRequest.SerializeToString,
                response_deserializer=coach__pb2.WorkoutPlan.FromString,
                _registered_method=True)


class WorkoutGeneratorServiceServicer(object):
    """=============================================
    Service 2 - Workout Generator
    =============================================
    """

    def GenerateWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkoutGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateWorkout,
                    request_deserializer=coach__pb2.WorkoutRequest.FromString,
                    response_serializer=coach__pb2.WorkoutPlan.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coachpb.WorkoutGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coachpb.WorkoutGeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkoutGeneratorService(object):
    """=============================================
    Service 2 - Workout Generator
    =============================================
    """

    @staticmethod
    def GenerateWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coachpb.WorkoutGeneratorService/GenerateWorkout',
            coach__pb2.WorkoutRequest.SerializeToString,
            coach__pb2.WorkoutPlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProgressAnalyzerServiceStub(object):
    """=============================================
    Service 3 - Progress Analyzer
    =============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeProgress = channel.unary_unary(
                '/coachpb.ProgressAnalyzerService/AnalyzeProgress',
                request_serializer=coach__pb2.ProgressRequest.SerializeToString,
                response_deserializer=coach__pb2.InsightResponse.FromString,
                _registered_method=True)


class ProgressAnalyzerServiceServicer(object):
    """=============================================
    Service 3 - Progress Analyzer
    =============================================
    """

    def AnalyzeProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProgressAnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeProgress,
                    request_deserializer=coach__pb2.ProgressRequest.FromString,
                    response_serializer=coach__pb2.InsightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coachpb.ProgressAnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coachpb.ProgressAnalyzerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProgressAnalyzerService(object):
    """=============================================
    Service 3 - Progress Analyzer
    =============================================
    """

    @staticmethod
    def AnalyzeProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coachpb.ProgressAnalyzerService/AnalyzeProgress',
            coach__pb2.ProgressRequest.SerializeToString,
            coach__pb2.InsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
