// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: coach.proto

package coachpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserProfile   *UserProfile           `protobuf:"bytes,3,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	ChatHistory   []*ChatMessage         `protobuf:"bytes,4,rep,name=chat_history,json=chatHistory,proto3" json:"chat_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_coach_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *ChatRequest) GetChatHistory() []*ChatMessage {
	if x != nil {
		return x.ChatHistory
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_coach_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // Ex: "user" or "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_coach_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type WorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserProfile   *UserProfile           `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	Workout       string                 `protobuf:"bytes,3,opt,name=workout,proto3" json:"workout,omitempty"` // Ex: "full-body" or "upper" or "lower"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutRequest) Reset() {
	*x = WorkoutRequest{}
	mi := &file_coach_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutRequest) ProtoMessage() {}

func (x *WorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutRequest.ProtoReflect.Descriptor instead.
func (*WorkoutRequest) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{3}
}

func (x *WorkoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkoutRequest) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *WorkoutRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

type WorkoutPlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Day               string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Focus             string                 `protobuf:"bytes,2,opt,name=focus,proto3" json:"focus,omitempty"` // Ex: "Upper body strength"
	Exercises         []*Exercise            `protobuf:"bytes,3,rep,name=exercises,proto3" json:"exercises,omitempty"`
	TotalDurationMins int32                  `protobuf:"varint,4,opt,name=total_duration_mins,json=totalDurationMins,proto3" json:"total_duration_mins,omitempty"`
	Difficulty        string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // Ex: "beginner" or "intermediate" or "advanced"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkoutPlan) Reset() {
	*x = WorkoutPlan{}
	mi := &file_coach_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutPlan) ProtoMessage() {}

func (x *WorkoutPlan) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutPlan.ProtoReflect.Descriptor instead.
func (*WorkoutPlan) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{4}
}

func (x *WorkoutPlan) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *WorkoutPlan) GetFocus() string {
	if x != nil {
		return x.Focus
	}
	return ""
}

func (x *WorkoutPlan) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *WorkoutPlan) GetTotalDurationMins() int32 {
	if x != nil {
		return x.TotalDurationMins
	}
	return 0
}

func (x *WorkoutPlan) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type Exercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sets          int32                  `protobuf:"varint,2,opt,name=sets,proto3" json:"sets,omitempty"`
	Reps          string                 `protobuf:"bytes,3,opt,name=reps,proto3" json:"reps,omitempty"` // Ex: "8-12 reps" or "to failure"
	RestSeconds   int32                  `protobuf:"varint,4,opt,name=rest_seconds,json=restSeconds,proto3" json:"rest_seconds,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_coach_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{5}
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetSets() int32 {
	if x != nil {
		return x.Sets
	}
	return 0
}

func (x *Exercise) GetReps() string {
	if x != nil {
		return x.Reps
	}
	return ""
}

func (x *Exercise) GetRestSeconds() int32 {
	if x != nil {
		return x.RestSeconds
	}
	return 0
}

func (x *Exercise) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorkoutLogs   []*WorkoutLog          `protobuf:"bytes,2,rep,name=workout_logs,json=workoutLogs,proto3" json:"workout_logs,omitempty"` // Last 30 days of data
	UserProfile   *UserProfile           `protobuf:"bytes,3,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_coach_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressRequest) GetWorkoutLogs() []*WorkoutLog {
	if x != nil {
		return x.WorkoutLogs
	}
	return nil
}

func (x *ProgressRequest) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

type InsightResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Summary         string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Insights        []*Insight             `protobuf:"bytes,2,rep,name=insights,proto3" json:"insights,omitempty"`
	Recommendations []string               `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsightResponse) Reset() {
	*x = InsightResponse{}
	mi := &file_coach_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightResponse) ProtoMessage() {}

func (x *InsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightResponse.ProtoReflect.Descriptor instead.
func (*InsightResponse) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{7}
}

func (x *InsightResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *InsightResponse) GetInsights() []*Insight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *InsightResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type Insight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // Ex: "strength_trend" or "consistency" or "recovery"
	Observation   string                 `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	Impact        string                 `protobuf:"bytes,3,opt,name=impact,proto3" json:"impact,omitempty"` // Ex: "positive", "neutral", "needs_attention"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Insight) Reset() {
	*x = Insight{}
	mi := &file_coach_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insight) ProtoMessage() {}

func (x *Insight) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insight.ProtoReflect.Descriptor instead.
func (*Insight) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{8}
}

func (x *Insight) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Insight) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

func (x *Insight) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

// =============================================
// Shared Models
// =============================================
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	FitnessGoal   string                 `protobuf:"bytes,4,opt,name=fitness_goal,json=fitnessGoal,proto3" json:"fitness_goal,omitempty"`    // Ex: "build_muscle" or "loose weight" or "general_fitness"
	FitnessLevel  string                 `protobuf:"bytes,5,opt,name=fitness_level,json=fitnessLevel,proto3" json:"fitness_level,omitempty"` // Ex: "beginner" or "intermediate" or "advanced"
	Equipment     []string               `protobuf:"bytes,6,rep,name=equipment,proto3" json:"equipment,omitempty"`                           // Ex: ["dumbbells", "barbell", "pull_up_bar"]
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_coach_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{9}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserProfile) GetFitnessGoal() string {
	if x != nil {
		return x.FitnessGoal
	}
	return ""
}

func (x *UserProfile) GetFitnessLevel() string {
	if x != nil {
		return x.FitnessLevel
	}
	return ""
}

func (x *UserProfile) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *UserProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type WorkoutLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // ISO format: "2026-01-10"
	ExerciseLogs  []*ExerciseLog         `protobuf:"bytes,3,rep,name=exercise_logs,json=exerciseLogs,proto3" json:"exercise_logs,omitempty"`
	DurationMins  int32                  `protobuf:"varint,4,opt,name=duration_mins,json=durationMins,proto3" json:"duration_mins,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutLog) Reset() {
	*x = WorkoutLog{}
	mi := &file_coach_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutLog) ProtoMessage() {}

func (x *WorkoutLog) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutLog.ProtoReflect.Descriptor instead.
func (*WorkoutLog) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{10}
}

func (x *WorkoutLog) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *WorkoutLog) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WorkoutLog) GetExerciseLogs() []*ExerciseLog {
	if x != nil {
		return x.ExerciseLogs
	}
	return nil
}

func (x *WorkoutLog) GetDurationMins() int32 {
	if x != nil {
		return x.DurationMins
	}
	return 0
}

func (x *WorkoutLog) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ExerciseLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepsPerSet    []int32                `protobuf:"varint,2,rep,packed,name=reps_per_set,json=repsPerSet,proto3" json:"reps_per_set,omitempty"`
	WeightPerSet  []float32              `protobuf:"fixed32,3,rep,packed,name=weight_per_set,json=weightPerSet,proto3" json:"weight_per_set,omitempty"` // in kg
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseLog) Reset() {
	*x = ExerciseLog{}
	mi := &file_coach_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseLog) ProtoMessage() {}

func (x *ExerciseLog) ProtoReflect() protoreflect.Message {
	mi := &file_coach_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseLog.ProtoReflect.Descriptor instead.
func (*ExerciseLog) Descriptor() ([]byte, []int) {
	return file_coach_proto_rawDescGZIP(), []int{11}
}

func (x *ExerciseLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExerciseLog) GetRepsPerSet() []int32 {
	if x != nil {
		return x.RepsPerSet
	}
	return nil
}

func (x *ExerciseLog) GetWeightPerSet() []float32 {
	if x != nil {
		return x.WeightPerSet
	}
	return nil
}

func (x *ExerciseLog) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_coach_proto protoreflect.FileDescriptor

const file_coach_proto_rawDesc = "" +
	"\n" +
	"\vcoach.proto\x12\acoachpb\"\xb2\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\fuser_profile\x18\x03 \x01(\v2\x14.coachpb.UserProfileR\vuserProfile\x127\n" +
	"\fchat_history\x18\x04 \x03(\v2\x14.coachpb.ChatMessageR\vchatHistory\"I\n" +
	"\fChatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\x05R\n" +
	"tokensUsed\"Y\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"|\n" +
	"\x0eWorkoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\fuser_profile\x18\x02 \x01(\v2\x14.coachpb.UserProfileR\vuserProfile\x12\x18\n" +
	"\aworkout\x18\x03 \x01(\tR\aworkout\"\xb6\x01\n" +
	"\vWorkoutPlan\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x14\n" +
	"\x05focus\x18\x02 \x01(\tR\x05focus\x12/\n" +
	"\texercises\x18\x03 \x03(\v2\x11.coachpb.ExerciseR\texercises\x12.\n" +
	"\x13total_duration_mins\x18\x04 \x01(\x05R\x11totalDurationMins\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\"\x7f\n" +
	"\bExercise\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04sets\x18\x02 \x01(\x05R\x04sets\x12\x12\n" +
	"\x04reps\x18\x03 \x01(\tR\x04reps\x12!\n" +
	"\frest_seconds\x18\x04 \x01(\x05R\vrestSeconds\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\x9b\x01\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\fworkout_logs\x18\x02 \x03(\v2\x13.coachpb.WorkoutLogR\vworkoutLogs\x127\n" +
	"\fuser_profile\x18\x03 \x01(\v2\x14.coachpb.UserProfileR\vuserProfile\"\x83\x01\n" +
	"\x0fInsightResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12,\n" +
	"\binsights\x18\x02 \x03(\v2\x10.coachpb.InsightR\binsights\x12(\n" +
	"\x0frecommendations\x18\x03 \x03(\tR\x0frecommendations\"_\n" +
	"\aInsight\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12 \n" +
	"\vobservation\x18\x02 \x01(\tR\vobservation\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\tR\x06impact\"\xca\x01\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12!\n" +
	"\ffitness_goal\x18\x04 \x01(\tR\vfitnessGoal\x12#\n" +
	"\rfitness_level\x18\x05 \x01(\tR\ffitnessLevel\x12\x1c\n" +
	"\tequipment\x18\x06 \x03(\tR\tequipment\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\"\xad\x01\n" +
	"\n" +
	"WorkoutLog\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x129\n" +
	"\rexercise_logs\x18\x03 \x03(\v2\x14.coachpb.ExerciseLogR\fexerciseLogs\x12#\n" +
	"\rduration_mins\x18\x04 \x01(\x05R\fdurationMins\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\x7f\n" +
	"\vExerciseLog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\freps_per_set\x18\x02 \x03(\x05R\n" +
	"repsPerSet\x12$\n" +
	"\x0eweight_per_set\x18\x03 \x03(\x02R\fweightPerSet\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes2N\n" +
	"\x10CoachChatService\x12:\n" +
	"\vSendMessage\x12\x14.coachpb.ChatRequest\x1a\x15.coachpb.ChatResponse2[\n" +
	"\x17WorkoutGeneratorService\x12@\n" +
	"\x0fGenerateWorkout\x12\x17.coachpb.WorkoutRequest\x1a\x14.coachpb.WorkoutPlan2`\n" +
	"\x17ProgressAnalyzerService\x12E\n" +
	"\x0fAnalyzeProgress\x12\x18.coachpb.ProgressRequest\x1a\x18.coachpb.InsightResponseBSZQgithub.com/ManoVikram/AI-Personal-Fitness-Coach/backend/api/proto/coachpb;coachpbb\x06proto3"

var (
	file_coach_proto_rawDescOnce sync.Once
	file_coach_proto_rawDescData []byte
)

func file_coach_proto_rawDescGZIP() []byte {
	file_coach_proto_rawDescOnce.Do(func() {
		file_coach_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coach_proto_rawDesc), len(file_coach_proto_rawDesc)))
	})
	return file_coach_proto_rawDescData
}

var file_coach_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_coach_proto_goTypes = []any{
	(*ChatRequest)(nil),     // 0: coachpb.ChatRequest
	(*ChatResponse)(nil),    // 1: coachpb.ChatResponse
	(*ChatMessage)(nil),     // 2: coachpb.ChatMessage
	(*WorkoutRequest)(nil),  // 3: coachpb.WorkoutRequest
	(*WorkoutPlan)(nil),     // 4: coachpb.WorkoutPlan
	(*Exercise)(nil),        // 5: coachpb.Exercise
	(*ProgressRequest)(nil), // 6: coachpb.ProgressRequest
	(*InsightResponse)(nil), // 7: coachpb.InsightResponse
	(*Insight)(nil),         // 8: coachpb.Insight
	(*UserProfile)(nil),     // 9: coachpb.UserProfile
	(*WorkoutLog)(nil),      // 10: coachpb.WorkoutLog
	(*ExerciseLog)(nil),     // 11: coachpb.ExerciseLog
}
var file_coach_proto_depIdxs = []int32{
	9,  // 0: coachpb.ChatRequest.user_profile:type_name -> coachpb.UserProfile
	2,  // 1: coachpb.ChatRequest.chat_history:type_name -> coachpb.ChatMessage
	9,  // 2: coachpb.WorkoutRequest.user_profile:type_name -> coachpb.UserProfile
	5,  // 3: coachpb.WorkoutPlan.exercises:type_name -> coachpb.Exercise
	10, // 4: coachpb.ProgressRequest.workout_logs:type_name -> coachpb.WorkoutLog
	9,  // 5: coachpb.ProgressRequest.user_profile:type_name -> coachpb.UserProfile
	8,  // 6: coachpb.InsightResponse.insights:type_name -> coachpb.Insight
	11, // 7: coachpb.WorkoutLog.exercise_logs:type_name -> coachpb.ExerciseLog
	0,  // 8: coachpb.CoachChatService.SendMessage:input_type -> coachpb.ChatRequest
	3,  // 9: coachpb.WorkoutGeneratorService.GenerateWorkout:input_type -> coachpb.WorkoutRequest
	6,  // 10: coachpb.ProgressAnalyzerService.AnalyzeProgress:input_type -> coachpb.ProgressRequest
	1,  // 11: coachpb.CoachChatService.SendMessage:output_type -> coachpb.ChatResponse
	4,  // 12: coachpb.WorkoutGeneratorService.GenerateWorkout:output_type -> coachpb.WorkoutPlan
	7,  // 13: coachpb.ProgressAnalyzerService.AnalyzeProgress:output_type -> coachpb.InsightResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_coach_proto_init() }
func file_coach_proto_init() {
	if File_coach_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coach_proto_rawDesc), len(file_coach_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_coach_proto_goTypes,
		DependencyIndexes: file_coach_proto_depIdxs,
		MessageInfos:      file_coach_proto_msgTypes,
	}.Build()
	File_coach_proto = out.File
	file_coach_proto_goTypes = nil
	file_coach_proto_depIdxs = nil
}
