// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: coach.proto

package coachpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoachChatService_SendMessage_FullMethodName = "/coachpb.CoachChatService/SendMessage"
)

// CoachChatServiceClient is the client API for CoachChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================
// Service 1 - Coach Chat
// =============================================
type CoachChatServiceClient interface {
	SendMessage(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type coachChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoachChatServiceClient(cc grpc.ClientConnInterface) CoachChatServiceClient {
	return &coachChatServiceClient{cc}
}

func (c *coachChatServiceClient) SendMessage(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, CoachChatService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoachChatServiceServer is the server API for CoachChatService service.
// All implementations must embed UnimplementedCoachChatServiceServer
// for forward compatibility.
//
// =============================================
// Service 1 - Coach Chat
// =============================================
type CoachChatServiceServer interface {
	SendMessage(context.Context, *ChatRequest) (*ChatResponse, error)
	mustEmbedUnimplementedCoachChatServiceServer()
}

// UnimplementedCoachChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoachChatServiceServer struct{}

func (UnimplementedCoachChatServiceServer) SendMessage(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedCoachChatServiceServer) mustEmbedUnimplementedCoachChatServiceServer() {}
func (UnimplementedCoachChatServiceServer) testEmbeddedByValue()                          {}

// UnsafeCoachChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoachChatServiceServer will
// result in compilation errors.
type UnsafeCoachChatServiceServer interface {
	mustEmbedUnimplementedCoachChatServiceServer()
}

func RegisterCoachChatServiceServer(s grpc.ServiceRegistrar, srv CoachChatServiceServer) {
	// If the following call panics, it indicates UnimplementedCoachChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoachChatService_ServiceDesc, srv)
}

func _CoachChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoachChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachChatServiceServer).SendMessage(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoachChatService_ServiceDesc is the grpc.ServiceDesc for CoachChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoachChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coachpb.CoachChatService",
	HandlerType: (*CoachChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _CoachChatService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coach.proto",
}

const (
	WorkoutGeneratorService_GenerateWorkout_FullMethodName = "/coachpb.WorkoutGeneratorService/GenerateWorkout"
)

// WorkoutGeneratorServiceClient is the client API for WorkoutGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================
// Service 2 - Workout Generator
// =============================================
type WorkoutGeneratorServiceClient interface {
	GenerateWorkout(ctx context.Context, in *WorkoutRequest, opts ...grpc.CallOption) (*WorkoutPlan, error)
}

type workoutGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutGeneratorServiceClient(cc grpc.ClientConnInterface) WorkoutGeneratorServiceClient {
	return &workoutGeneratorServiceClient{cc}
}

func (c *workoutGeneratorServiceClient) GenerateWorkout(ctx context.Context, in *WorkoutRequest, opts ...grpc.CallOption) (*WorkoutPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkoutPlan)
	err := c.cc.Invoke(ctx, WorkoutGeneratorService_GenerateWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutGeneratorServiceServer is the server API for WorkoutGeneratorService service.
// All implementations must embed UnimplementedWorkoutGeneratorServiceServer
// for forward compatibility.
//
// =============================================
// Service 2 - Workout Generator
// =============================================
type WorkoutGeneratorServiceServer interface {
	GenerateWorkout(context.Context, *WorkoutRequest) (*WorkoutPlan, error)
	mustEmbedUnimplementedWorkoutGeneratorServiceServer()
}

// UnimplementedWorkoutGeneratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutGeneratorServiceServer struct{}

func (UnimplementedWorkoutGeneratorServiceServer) GenerateWorkout(context.Context, *WorkoutRequest) (*WorkoutPlan, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateWorkout not implemented")
}
func (UnimplementedWorkoutGeneratorServiceServer) mustEmbedUnimplementedWorkoutGeneratorServiceServer() {
}
func (UnimplementedWorkoutGeneratorServiceServer) testEmbeddedByValue() {}

// UnsafeWorkoutGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutGeneratorServiceServer will
// result in compilation errors.
type UnsafeWorkoutGeneratorServiceServer interface {
	mustEmbedUnimplementedWorkoutGeneratorServiceServer()
}

func RegisterWorkoutGeneratorServiceServer(s grpc.ServiceRegistrar, srv WorkoutGeneratorServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkoutGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutGeneratorService_ServiceDesc, srv)
}

func _WorkoutGeneratorService_GenerateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutGeneratorServiceServer).GenerateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutGeneratorService_GenerateWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutGeneratorServiceServer).GenerateWorkout(ctx, req.(*WorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutGeneratorService_ServiceDesc is the grpc.ServiceDesc for WorkoutGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coachpb.WorkoutGeneratorService",
	HandlerType: (*WorkoutGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateWorkout",
			Handler:    _WorkoutGeneratorService_GenerateWorkout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coach.proto",
}

const (
	ProgressAnalyzerService_AnalyzeProgress_FullMethodName = "/coachpb.ProgressAnalyzerService/AnalyzeProgress"
)

// ProgressAnalyzerServiceClient is the client API for ProgressAnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================
// Service 3 - Progress Analyzer
// =============================================
type ProgressAnalyzerServiceClient interface {
	AnalyzeProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*InsightResponse, error)
}

type progressAnalyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgressAnalyzerServiceClient(cc grpc.ClientConnInterface) ProgressAnalyzerServiceClient {
	return &progressAnalyzerServiceClient{cc}
}

func (c *progressAnalyzerServiceClient) AnalyzeProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*InsightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsightResponse)
	err := c.cc.Invoke(ctx, ProgressAnalyzerService_AnalyzeProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgressAnalyzerServiceServer is the server API for ProgressAnalyzerService service.
// All implementations must embed UnimplementedProgressAnalyzerServiceServer
// for forward compatibility.
//
// =============================================
// Service 3 - Progress Analyzer
// =============================================
type ProgressAnalyzerServiceServer interface {
	AnalyzeProgress(context.Context, *ProgressRequest) (*InsightResponse, error)
	mustEmbedUnimplementedProgressAnalyzerServiceServer()
}

// UnimplementedProgressAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgressAnalyzerServiceServer struct{}

func (UnimplementedProgressAnalyzerServiceServer) AnalyzeProgress(context.Context, *ProgressRequest) (*InsightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeProgress not implemented")
}
func (UnimplementedProgressAnalyzerServiceServer) mustEmbedUnimplementedProgressAnalyzerServiceServer() {
}
func (UnimplementedProgressAnalyzerServiceServer) testEmbeddedByValue() {}

// UnsafeProgressAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgressAnalyzerServiceServer will
// result in compilation errors.
type UnsafeProgressAnalyzerServiceServer interface {
	mustEmbedUnimplementedProgressAnalyzerServiceServer()
}

func RegisterProgressAnalyzerServiceServer(s grpc.ServiceRegistrar, srv ProgressAnalyzerServiceServer) {
	// If the following call panics, it indicates UnimplementedProgressAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgressAnalyzerService_ServiceDesc, srv)
}

func _ProgressAnalyzerService_AnalyzeProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressAnalyzerServiceServer).AnalyzeProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressAnalyzerService_AnalyzeProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressAnalyzerServiceServer).AnalyzeProgress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgressAnalyzerService_ServiceDesc is the grpc.ServiceDesc for ProgressAnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgressAnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coachpb.ProgressAnalyzerService",
	HandlerType: (*ProgressAnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeProgress",
			Handler:    _ProgressAnalyzerService_AnalyzeProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coach.proto",
}
